### ISSUE TITLE
Send founds from my address to other address

### ISSUE THREAD

**Issue by merlinkory** [tonlabs/ton-client-node-js#39]
I have key pair.
i have generated address and sent TON Crystals to it.

How  i can send my TON Crystals to other wallets? 
I can't find this method.

**Comment by mnogoborec** [comment]
Your contract should contain such function. In TON only contracts can send Crystals with internal messages. You can call the contract function using `run` function of SDK

**Comment by merlinkory** [comment]
thank you)
