### ISSUE TITLE
Error Deploying contracts

### ISSUE THREAD

**Issue by Ren14** [tonlabs/ton-client-node-js#6]
Hello ! 

I am doing the SDK tutorial with the Node JS library.

at the stage of Deploying contracts I find the following error

`{source: 'sdk',
   code: 2004,
   message:
    'Invalid address [SizeError]: 0: 841288ed3b55d9cdafa806807f02a0ae0c169aa5edfe88a789a6482429756a94'}`

Can you help me ?

This mi code

const { TONClient } = require('ton-client-node-js');

// Define contract package

const HelloContract = require('./helloContract');

// Define keys for our contract

const helloKeys = {
    public: '55d7bab463a6a3ef5e03bb5f975836ddfb589b9ccb00329be7da8ea981c5268a',
    secret: 'de93a97c7103c2d44e47972265cfdfe266fd28c8cadc4875804ee9f57cf786d6',
};

const giverAddress = '0:841288ed3b55d9cdafa806807f02a0ae0c169aa5edfe88a789a6482429756a94';
const giverAbi = 
{
	"ABI version": 0,
	"functions": [
		{
			"name": "constructor",
			"inputs": [],
			"outputs": []
		},
		{
			"name": "sendGrams",
			"inputs": [
				{"name":"dest","type":"address"},
				{"name":"amount","type":"uint64"}
			],
			"outputs": []
		}
	],
	"events": [],
	"data": []
};

(async () => {
    try {
        const client = new TONClient();
        client.config.setData({
            servers: ['http://0.0.0.0']
        });
        await client.setup();
        await main(client);
        console.log('Hello TON Done');
    process.exit(0);
    } catch (error) {        
        console.error(error);
    }
})();

async function get_grams_from_giver(client, account) {    
    const { contracts, queries } = client;
    const result = await contracts.run({
        address: giverAddress,
        functionName: 'sendGrams',
        abi: giverAbi,
        input: {
            dest: `account`,
            amount: 5000000000
        },
        keyPair: null,
    });

    const wait = await queries.accounts.waitFor(
        {
            id: { eq: account },
            balance: { gt: "0" }
        },
		'id balance'
    );
};

async function main(client) {  
    // <<<<< La siguiente sentencia arroja el error  >>>>>
    const futureHelloAddress = (await client.contracts.createDeployMessage({
        package: HelloContract.package,
        constructorParams: {},
        keyPair: helloKeys,
    })).address;

    console.log(`Future address of the contract will be: ${futureHelloAddress}`);

    await get_grams_from_giver(client, futureHelloAddress);
    console.log(`Grams were transfered from giver to ${futureHelloAddress}`);

    const helloAddress = (await client.contracts.deploy({
        package: HelloContract.package,
        constructorParams: {},
        keyPair: helloKeys,
    })).address;
    console.log(`Hello contract was deployed at address: ${helloAddress});
}

**Comment by AlexeyVavilin** [comment]
You probably use the older version of SDK which doesn't support full addresses. Try to update SDK by removing `node_modules` folder end running`npm install`. 0.16.0 SDK version should be used. Node SE should also be 0.16.0. You can switch Node SE version by `tondev use` command. `tondev` tool was also updated in last release so you can update it to the new version.
There is also a little error in documentation. You shuold pass `dest: account` with account parameter value, not `dest: 'account'` with string `account`. 
And one more: use of pre-generated keys is not a good idea now. Second deploy to the same address will cause error because contract constructor could be called only once. You'd better use `client.crypto.ed25519Keypair` function to generate key pair each time. Documentation will be updated soon

**Comment by Ren14** [comment]
Thank you. I applied your recommendations. use this command to generate the new keys `sudo tondev keys`

Is my tondev well configured? I still can't deploy the contract

![image](https://user-images.githubusercontent.com/3924497/68971109-90f3bb00-07c7-11ea-952c-88b211bbfe99.png)

This is my new code.

(...) 

(async () => {
    try {
        const client = new TONClient();
        client.config.setData({
            servers: ['http://0.0.0.0']
        });
        await client.setup();
        await main(client);
        console.log('Hello TON Done');
    process.exit(0);
    } catch (error) {        
        console.error(error);
        process.exit(0);
    }
})();

async function get_grams_from_giver(client, **account**) {    
    const { contracts, queries } = client;
    const result = await contracts.run({
        address: giverAddress,
        functionName: 'sendGrams',
        abi: giverAbi,
        input: {
            dest: **account**,
            amount: 5000000000
        },
        keyPair: null,
    });

    const wait = await queries.accounts.waitFor(
        {
            id: { eq: account },
            balance: { gt: "0" }
        },
		'id balance'
    );
};

async function main(client) {  
    **// <<<<< La siguiente sentencia arroja el error  >>>>>**
    const futureHelloAddress = (await client.contracts.createDeployMessage({
        package: HelloContract.package,
        constructorParams: {},
        keyPair: helloKeys,
    })).address;

    console.log(`Future address of the contract will be: ${futureHelloAddress}`);

    await get_grams_from_giver(client, futureHelloAddress);
    console.log(`Grams were transfered from giver to ${futureHelloAddress}`);

    const helloAddress = (await client.contracts.deploy({
        package: HelloContract.package,
        constructorParams: {},
        keyPair: helloKeys,
    })).address;
    console.log(`Hello contract was deployed at address: ${helloAddress}`);
}

**Comment by Ren14** [comment]
I found the error. thanks to Алексей Вавилин.
the error was in the dependency declared in the package.json file

`"dependencies": {
    "ton-client-node-js": "^0.16.0"
  }`

Once the latest version is indicated, you must update the packages.

finally, when the contract must be executed, you must use the runLocal function instead of run, described in the next section
https://zeroheight.com/86757ecb2/p/665008/t/727de9
